// ─────────────────────────────────────────────────────────────────────────────
// EcoTap — Global TypeScript types
// Every DB table has a matching interface here. No inline types in components.
// ─────────────────────────────────────────────────────────────────────────────

// ── Enums ─────────────────────────────────────────────────────────────────────

export type UserRole =
  | "super_admin"   // Platform owner — full access
  | "country_rep"   // Regional rep — read-only admin dashboard, filtered by country
  | "company_admin" // Legal rep of a company (CEO or HR) — manages employees
  | "employee"      // Under a company subscription — theme controlled by company if locked
  | "individual";   // Self-paying — full control over card and theme

export type UserStatus      = "pending" | "active" | "suspended";
export type OrderStatus     = "pending" | "approved" | "shipped" | "delivered";
export type BillingCycle    = "monthly" | "annual";
export type SubscriptionStatus = "active" | "inactive" | "cancelled";
export type InvitationStatus   = "pending" | "accepted" | "expired";

export type DeviceType = "mobile" | "tablet" | "desktop" | "unknown";

export type EventType =
  | "view"             // Card page opened
  | "nfc_tap"          // Arrived via NFC chip (?source=nfc)
  | "qr_scan"          // Arrived via QR code (?source=qr)
  | "vcf_download"     // Save contact button clicked
  | "contact_exchange" // Visitor submitted their contact details
  | "social_click"     // A social link icon clicked
  | "share";           // Card shared (future)

// ── Identity & access ─────────────────────────────────────────────────────────

export interface Profile {
  id:         string;
  role:       UserRole;
  status:     UserStatus;
  username:   string;
  full_name:  string;
  email:      string;
  avatar_url: string | null;
  created_at: string;
  updated_at: string;
}

export interface Company {
  id:                    string;
  name:                  string;
  slug:                  string;
  logo_url:              string | null;
  brand_color:           string | null;
  industry:              string | null;
  website:               string | null;
  size:                  string | null;
  description:           string | null;
  status:                UserStatus;
  /** If true, employees under this company cannot change their card theme_color */
  theme_locked:          boolean;
  /** Captured at registration — legal rep confirmation checkbox */
  legal_rep_confirmed:   boolean;
  /** Optional company-level social links — shared across all employees */
  social_links:          SocialLinks | null;
  created_at:            string;
  updated_at:            string;
}

/**
 * Links a profile (country_rep role) to a country code.
 * A country rep can only view users/companies in their assigned country.
 */
export interface CountryRep {
  id:           string;
  profile_id:   string;
  country_code: string;  // ISO 3166-1 alpha-2 e.g. "RW", "UG", "KE"
  country_name: string;
  created_at:   string;
}

/**
 * Many-to-many: a user can be linked to multiple companies.
 * is_primary = true → this company shows in the card top-right badge.
 * Any user can link to any company — no company confirmation required.
 * Company only controls card if the employee is under their subscription.
 */
export interface ProfileCompany {
  id:            string;
  profile_id:    string;
  company_id:    string;
  department_id: string | null;
  job_title:     string | null;  // Role at this specific company
  is_primary:    boolean;
  created_at:    string;
}

/** An editable affiliation group on a digital card. Max 3 per card. */
export interface CardGroup {
  id:                string;
  card_id:           string;
  organization_name: string;
  job_title:         string | null;
  social_links:      SocialLinks;
  show_on_card:      boolean;
  sort_order:        number;
  created_at:        string;
  updated_at:        string;
}

export interface Department {
  id:         string;
  company_id: string;
  name:       string;
  color:      string | null;
  created_at: string;
}

/**
 * One-time-use invite links generated by company admins.
 * Token expires after 7 days and can only be used once.
 */
export interface Invitation {
  id:          string;
  company_id:  string;
  created_by:  string;         // profile_id of the company admin
  email:       string | null;  // Optional — pre-fills the registration form
  token:       string;         // Unique one-time token in the invite URL
  status:      InvitationStatus;
  expires_at:  string;
  accepted_by: string | null;  // profile_id of the employee who accepted
  created_at:  string;
}

// ── Cards & orders ────────────────────────────────────────────────────────────

export interface SocialLinks {
  linkedin?:  string;
  twitter?:   string;
  whatsapp?:  string;
  instagram?: string;
  website?:   string;
}

/**
 * Digital card — one per profile.
 * theme_color is the digital accent colour, independent of the physical card design.
 * If the user's primary company has theme_locked = true, theme_color cannot be edited.
 */
export interface Card {
  id:               string;
  profile_id:       string;
  slug:             string;
  theme_color:      string;        // Digital card accent colour (#hex)
  bio:              string | null;
  job_title:        string | null; // Fallback if no primary company job_title set
  phone:            string | null;
  email_public:     string | null; // Shown on card (may differ from auth email)
  social_links:     SocialLinks;
  show_organization:boolean;       // Show company, department, job title, company socials on card
  qr_url:           string | null;
  is_public:        boolean;
  created_at:       string;
  updated_at:       string;
}

/** Physical NFC card designs — managed by Super Admin. Independent of theme_color. */
export interface CardDesign {
  id:           string;
  name:         string;
  description:  string | null;
  preview_url:  string | null;
  accent_color: string;
  pattern:      string;
  is_active:    boolean;
  created_at:   string;
}

export interface ShippingAddress {
  street:       string;
  city:         string;
  country:      string;
  postal_code?: string;
  notes?:       string;
}

export interface CardOrder {
  id:                     string;
  profile_id:             string;
  design_id:              string;
  quantity:               number;
  shipping_address:       ShippingAddress;
  status:                 OrderStatus;
  tracking_info:          string | null;
  admin_notes:            string | null;
  payment_screenshot_url: string | null;
  payment_status:         string;      // 'unpaid' | 'paid' | 'verified'
  payment_amount:         number | null;
  payment_currency:       string;      // 'USD' | 'RWF'
  momo_phone:             string | null;
  created_at:             string;
  updated_at:             string;
}

// ── Analytics & ML ────────────────────────────────────────────────────────────

/**
 * Append-only event telemetry — every visitor action on a card page.
 * NEVER deleted. Foundation of all future analytics and ML work.
 * Captured fire-and-forget via /api/events — never blocks a page render.
 */
export interface CardEvent {
  id:                string;
  card_id:           string;
  event_type:        EventType;
  session_id:        string | null;  // Groups events from one visitor session
  visitor_id:        string | null;  // Anonymous, persisted in cookie for return detection
  is_return_visitor: boolean;        // Computed: true if visitor_id seen before for this card
  source:            string | null;  // 'nfc' | 'qr' | 'direct' — clean source column for ML
  referrer:          string | null;
  device_type:       DeviceType;
  os:                string | null;
  browser:           string | null;
  screen_resolution: string | null;  // e.g. '390x844' — for device profiling
  country:           string | null;  // From Vercel x-vercel-ip-country header
  city:              string | null;
  utm_source:        string | null;
  utm_medium:        string | null;
  utm_campaign:      string | null;
  social_target:     string | null;  // For social_click events — which platform
  duration_ms:       number | null;  // Time on page — populated on session end
  created_at:        string;
}

/**
 * Pre-aggregated daily rollups per card.
 * Computed nightly by a scheduled job. Dashboard queries read this, not card_events.
 * Keeps dashboards instant at scale regardless of event volume.
 */
export interface DailyCardStat {
  id:              string;
  card_id:         string;
  date:            string;        // YYYY-MM-DD
  views:           number;
  nfc_taps:        number;
  qr_scans:        number;
  vcf_downloads:   number;
  exchanges:       number;
  social_clicks:   number;
  unique_visitors: number;
  avg_duration_ms: number | null;
  top_country:     string | null;
  created_at:      string;
}

/**
 * Contact submission from a visitor on a public card page.
 * Enriched with device and referrer metadata for ML feature engineering.
 */
export interface ContactExchange {
  id:                   string;
  card_id:              string;
  visitor_name:         string;
  visitor_email:        string | null;
  visitor_phone:        string | null;
  visitor_organization: string | null;  // Optional org/company from the visitor
  message:              string | null;  // Optional short note from the visitor
  event_id:             string | null;  // Links to the card_events row for this session
  device_type:          DeviceType;
  referrer:             string | null;
  country:              string | null;
  created_at:           string;
}

/**
 * User lifecycle events — logins, profile updates, settings changes.
 * Critical for churn prediction and engagement scoring.
 */
export interface ProfileActivity {
  id:            string;
  profile_id:    string;
  activity_type: string;   // 'login' | 'profile_update' | 'settings_change' | 'card_edit' | 'order_placed'
  description:   string | null;  // Human-readable summary
  metadata:      Record<string, unknown>;  // Changed fields, previous values, context
  ip_address:    string | null;
  user_agent:    string | null;
  created_at:    string;
}

/**
 * Pre-computed ML scores per card. Updated by batch jobs.
 * Dashboards and recommendation engines read from here.
 */
export interface CardScore {
  id:               string;
  card_id:          string;
  engagement_score: number | null;  // 0.00–100.00
  quality_score:    number | null;  // 0.00–100.00
  churn_risk_score: number | null;  // 0.00–100.00
  influence_score:  number | null;  // 0.00–100.00
  score_version:    string;         // Model version that produced these scores
  computed_at:      string;
  created_at:       string;
}

/** A/B test variant assignment — which variant each visitor saw */
export interface ABTestAssignment {
  id:         string;
  test_id:    string;         // Unique test slug e.g. 'card_design_v2'
  variant:    string;         // Variant identifier e.g. 'control', 'emerald_bg'
  visitor_id: string | null;  // Anonymous cookie ID
  profile_id: string | null;  // Null for anonymous visitors
  card_id:    string | null;  // The card being tested
  metadata:   Record<string, unknown>;  // Extra context
  converted:  boolean | null; // Null = pending, true/false = outcome
  created_at: string;
}

// ── Billing & platform ────────────────────────────────────────────────────────

export interface BillingPlan {
  id:                 string;
  name:               string;
  billing_cycle:      BillingCycle;
  price_per_employee: number;  // In RWF
  is_active:          boolean;
  created_at:         string;
}

export interface CompanySubscription {
  id:                string;
  company_id:        string;
  plan_id:           string;
  status:            SubscriptionStatus;
  started_at:        string;       // Tenure start — for churn prediction
  employee_count:    number;
  next_billing_date: string | null;
  created_at:        string;
  updated_at:        string;
}

/** Notification log — tracks what was sent, to whom, and via which channel */
export interface Notification {
  id:         string;
  profile_id: string;                  // Recipient
  type:       NotificationType;
  title:      string;
  body:       string;
  is_read:    boolean;
  email_sent: boolean;
  metadata:   Record<string, unknown>; // Type-specific extra data
  created_at: string;
}

export type NotificationType =
  | "pending_approval_company"
  | "pending_approval_individual"
  | "card_order_placed"
  | "order_status_update";

/**
 * Monthly environmental impact report per company.
 * Calculated using industry-standard figures (see INSTRUCTIONS.md).
 * Stored so historical trends can be tracked — not recomputed retroactively.
 */
export interface EnvironmentalReport {
  id:                   string;
  company_id:           string;
  report_month:         string;   // YYYY-MM
  active_cards:         number;   // Employee cards active during this month
  cards_in_circulation: number;   // Total physical cards ever ordered (full lifecycle count)
  paper_cards_avoided:  number;   // Estimated paper cards not printed
  co2_saved_grams:      number;   // Grams of CO₂ avoided
  water_saved_litres:   number;   // Litres of water not consumed
  waste_avoided_grams:  number;   // Grams of paper waste avoided
  trees_saved:          number;   // Fractional tree equivalent
  cumulative_co2_grams: number;   // Running total since joining
  cumulative_cards:     number;   // Running total cards avoided
  email_sent:           boolean;
  email_sent_at:        string | null;
  created_at:           string;
}

// ── Joined / enriched types ───────────────────────────────────────────────────

/** Everything needed to render a public card page */
export interface PublicCard extends Card {
  profile: Pick<Profile, "id" | "username" | "full_name" | "email" | "avatar_url" | "role">;
  primary_company:   Pick<Company, "id" | "name" | "slug" | "logo_url" | "brand_color" | "theme_locked" | "social_links"> | null;
  primary_job_title: string | null;  // From profile_companies where is_primary = true
  all_companies:     Array<{
    company: Pick<Company, "id" | "name" | "slug">;
    job_title: string | null;
    department: string | null;
    is_primary: boolean;
  }>;
  card_groups: CardGroup[];  // Editable affiliation groups (max 3)
}

export interface CardOrderWithDesign extends CardOrder {
  design: CardDesign;
}

export interface ProfileWithCompanies extends Profile {
  companies: Array<ProfileCompany & {
    company:    Company;
    department: Department | null;
  }>;
}

// ── Admin dashboard types ──────────────────────────────────────────────────────

/** Full profile detail with card, orders, and company associations */
export interface ProfileFull extends Profile {
  card: Card | null;
  orders: CardOrderWithDesign[];
  companies: Array<ProfileCompany & {
    company: Company;
    department: Department | null;
  }>;
}

/** Company with related counts for admin detail views */
export interface CompanyWithRelations extends Company {
  memberCount: number;
  subscription: (CompanySubscription & { plan: BillingPlan }) | null;
  departmentCount: number;
}

/** Contact exchange enriched with card owner info for admin view */
export interface ContactExchangeWithOwner extends ContactExchange {
  card_owner: {
    profile_id: string;
    full_name: string;
    email: string;
    username: string;
  } | null;
}

/** Generic paginated result */
export interface PaginatedResult<T> {
  data: T[];
  total: number;
  page: number;
  totalPages: number;
}

// ── Form types ────────────────────────────────────────────────────────────────

export interface OrgRegisterForm {
  company_name:          string;
  industry:              string;
  size:                  string;
  website:               string;
  admin_name:            string;
  email:                 string;
  legal_rep_confirmed:   boolean; // Must be true to submit
}

export interface IndividualRegisterForm {
  full_name:     string;
  email:         string;
  username:      string;
  company_name?: string;
}

export interface CardProfileForm {
  job_title:         string;
  phone:             string;
  email_public:      string;
  bio:               string;
  theme_color:       string;
  social_links:      SocialLinks;
  show_organization: boolean;
}

export interface AddCompanyForm {
  company_name:  string;
  job_title:     string;
  is_primary:    boolean;
}

export interface OrderForm {
  design_id:        string;
  quantity:         number;
  shipping_address: ShippingAddress;
  payment_currency?: string;  // 'USD' | 'RWF'
  payment_amount?:   number;
  momo_phone?:       string;
}

export interface RecordEventPayload {
  card_id:           string;
  event_type:        EventType;
  session_id?:       string;
  visitor_id?:       string;
  is_return_visitor?:boolean;
  source?:           string;       // 'nfc' | 'qr' | 'direct'
  referrer?:         string;
  device_type?:      DeviceType;
  os?:               string;
  browser?:          string;
  screen_resolution?:string;       // e.g. '390x844'
  country?:          string;
  city?:             string;
  utm_source?:       string;
  utm_medium?:       string;
  utm_campaign?:     string;
  social_target?:    string;
}

// ── Server Action response ────────────────────────────────────────────────────

export interface ActionResult<T = void> {
  success: boolean;
  data?:   T;
  error?:  string;
}